<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>IBDD | Login</title>
</head></head>
<body>
    <div id="login">
        <fieldset>
<div id="form">

<form action=# id="form">
<p>Login</p>   
    <p> Digite os dados requeridos para acessar sua conta</p>
<label for="emailLogin"id="labelLogin"> Seu Email </label>         <br>               
<input type="email" name="emailLogin" id="input-emailLogin" required> <br>

<label for="senhaLogin"id="labelLogin"> Sua Senha </label>                 <br>        
<input type="password" name="senhaLogin" id="input-senhaLogin" required> <br>
<p><a href=#> Esqueceu a senha?</a></p>

<input type="checkbox" name="remember" id="remember"> 
<label for="remember" id="labelRemember">Lembrar de mim</label> <br>
<input type="submit" value="Login"><br>
<p><a href="SIGNUP.php"> Não tem login?</a></p></form>     
</div>
    </fieldset>
</div>

    </body>
